### ISSUE TITLE
Can't build vm and install windows on aarch64

### ISSUE THREAD

**Issue by taozuhong** [Goo-aw233/goo-aw233.github.io#2]
感谢您分享使用 qemu 构建 Windows ARM64 虚拟机的博文: [QEMU 安装 Windows ARM](https://goo-aw233.github.io/zh-CN/tutorial/VM/QEMU/WindowsARMonQEMU/#%E5%AE%9E%E9%AA%8C%E7%8E%AF%E5%A2%83)，详细过程和步骤很细致，还贴心的分享了过程中的关键细节，并做了更新升级；看得出来是一篇非常用心的匠心之作；

我跟随文章分享的步骤做了尝试，失败了，无法重现实验步骤，卡在了启动画面，我所使用的环境和版本如下：

Windows 11: 10.0.22631.3737
qemu: [9.0.1](https://qemu.weilnetz.de/w64/qemu-w64-setup-20240423.exe)
BIOS: 跟随文章指示从分享的目录中下载的；
驱动：virtio-win.iso，跟随文章指示下载的；
```
qemu-img create -f qcow2 E:\Machines\qemu\windows.qcow2 120G

qemu-system-aarch64.exe -M virt,virtualization=true -cpu cortex-a76 -smp 4 -m 6144 ^
-device qemu-xhci -device usb-kbd -device usb-tablet ^
-drive file=windows.qcow2,if=virtio ^
-nic user,model=virtio ^
-device virtio-gpu-pci ^
-drive file=E:\Softwares\Windows11.22621.ARM64_ZH-CN.ISO,media=cdrom,if=none,id=cdrom -device usb-storage,drive=cdrom ^
-drive file=virtio-win.iso,media=cdrom,if=none,id=cdrom1 -device usb-storage,drive=cdrom1 ^
-bios QEMU_EFI.fd -device ramfb ^
-drive file=vars-template-pflash.raw,if=pflash,index=1,format=raw
```

控制台输出如下：
```
(qemu:10668): Gtk-WARNING **: 16:01:57.231: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
```

![image](https://github.com/Goo-aw233/goo-aw233.github.io/assets/13451009/af4eee7b-9238-46d0-9914-2bd63438257c)

**Comment by taozuhong** [comment]
完全使用楼主分享的 qemu 版本和相关文件，再重走过程（Windows ISO 是我自己下载的），出现了熟悉的画面后进入了UEFI Shell
![image](https://github.com/Goo-aw233/goo-aw233.github.io/assets/13451009/a9d87a64-73f7-4ab4-9f45-8073b7013483)

![image](https://github.com/Goo-aw233/goo-aw233.github.io/assets/13451009/9eefc967-712d-411e-99de-040ef091492b)

**Comment by Goo-aw233** [comment]
> 完全使用楼主分享的 qemu 版本和相关文件，再重走过程（Windows ISO 是我自己下载的），出现了熟悉的画面后进入了UEFI Shell
> 
> ![image](https://github.com/Goo-aw233/goo-aw233.github.io/assets/13451009/a9d87a64-73f7-4ab4-9f45-8073b7013483)
> 
> 
> 
> ![image](https://github.com/Goo-aw233/goo-aw233.github.io/assets/13451009/9eefc967-712d-411e-99de-040ef091492b)

如果进入 UEFI Shell 的话，可能是因为 ISO 无法引导

你可以尝试以下的命令来通过 EFI 文件启动：

fs0:
ls
cd Boot
BOOTX64.efi

其中，fs0: 是指定磁盘，ls 是为了查看是否为正确的磁盘和目录，在找到 BOOTX64.efi 后直接输入名称后即可从该文件启动到 ISO

**Comment by taozuhong** [comment]
好的，我先下载楼主分享的安装包ISO文件试试；

**Comment by Goo-aw233** [comment]
> 感谢您分享使用 qemu 构建 Windows ARM64 虚拟机的博文: [QEMU 安装 Windows ARM](https://goo-aw233.github.io/zh-CN/tutorial/VM/QEMU/WindowsARMonQEMU/#%E5%AE%9E%E9%AA%8C%E7%8E%AF%E5%A2%83)，详细过程和步骤很细致，还贴心的分享了过程中的关键细节，并做了更新升级；看得出来是一篇非常用心的匠心之作；
> 
> 
> 
> 我跟随文章分享的步骤做了尝试，失败了，无法重现实验步骤，卡在了启动画面，我所使用的环境和版本如下：
> 
> 
> 
> Windows 11: 10.0.22631.3737
> 
> qemu: [9.0.1](https://qemu.weilnetz.de/w64/qemu-w64-setup-20240423.exe)
> 
> BIOS: 跟随文章指示从分享的目录中下载的；
> 
> 驱动：virtio-win.iso，跟随文章指示下载的；
> 
> ```
> 
> qemu-img create -f qcow2 E:\Machines\qemu\windows.qcow2 120G
> 
> 
> 
> qemu-system-aarch64.exe -M virt,virtualization=true -cpu cortex-a76 -smp 4 -m 6144 ^
> 
> -device qemu-xhci -device usb-kbd -device usb-tablet ^
> 
> -drive file=windows.qcow2,if=virtio ^
> 
> -nic user,model=virtio ^
> 
> -device virtio-gpu-pci ^
> 
> -drive file=E:\Softwares\Windows11.22621.ARM64_ZH-CN.ISO,media=cdrom,if=none,id=cdrom -device usb-storage,drive=cdrom ^
> 
> -drive file=virtio-win.iso,media=cdrom,if=none,id=cdrom1 -device usb-storage,drive=cdrom1 ^
> 
> -bios QEMU_EFI.fd -device ramfb ^
> 
> -drive file=vars-template-pflash.raw,if=pflash,index=1,format=raw
> 
> ```
> 
> 
> 
> 控制台输出如下：
> 
> ```
> 
> (qemu:10668): Gtk-WARNING **: 16:01:57.231: Could not load a pixbuf from icon theme.
> 
> This may indicate that pixbuf loaders or the mime database could not be found.
> 
> ```
> 
> 
> 
> ![image](https://github.com/Goo-aw233/goo-aw233.github.io/assets/13451009/af4eee7b-9238-46d0-9914-2bd63438257c)
> 
> 
> 
> 

此外，如果添加了 -device virtio-gpu 这行参数，建议移除，因为 virtio-gpu 只在系统安装对应的驱动之后才会显示，且可能显示不正确，使用 ramfb 就够（

**Comment by Goo-aw233** [comment]
> 感谢您分享使用 qemu 构建 Windows ARM64 虚拟机的博文: [QEMU 安装 Windows ARM](https://goo-aw233.github.io/zh-CN/tutorial/VM/QEMU/WindowsARMonQEMU/#%E5%AE%9E%E9%AA%8C%E7%8E%AF%E5%A2%83)，详细过程和步骤很细致，还贴心的分享了过程中的关键细节，并做了更新升级；看得出来是一篇非常用心的匠心之作；
> 
> 
> 
> 我跟随文章分享的步骤做了尝试，失败了，无法重现实验步骤，卡在了启动画面，我所使用的环境和版本如下：
> 
> 
> 
> Windows 11: 10.0.22631.3737
> 
> qemu: [9.0.1](https://qemu.weilnetz.de/w64/qemu-w64-setup-20240423.exe)
> 
> BIOS: 跟随文章指示从分享的目录中下载的；
> 
> 驱动：virtio-win.iso，跟随文章指示下载的；
> 
> ```
> 
> qemu-img create -f qcow2 E:\Machines\qemu\windows.qcow2 120G
> 
> 
> 
> qemu-system-aarch64.exe -M virt,virtualization=true -cpu cortex-a76 -smp 4 -m 6144 ^
> 
> -device qemu-xhci -device usb-kbd -device usb-tablet ^
> 
> -drive file=windows.qcow2,if=virtio ^
> 
> -nic user,model=virtio ^
> 
> -device virtio-gpu-pci ^
> 
> -drive file=E:\Softwares\Windows11.22621.ARM64_ZH-CN.ISO,media=cdrom,if=none,id=cdrom -device usb-storage,drive=cdrom ^
> 
> -drive file=virtio-win.iso,media=cdrom,if=none,id=cdrom1 -device usb-storage,drive=cdrom1 ^
> 
> -bios QEMU_EFI.fd -device ramfb ^
> 
> -drive file=vars-template-pflash.raw,if=pflash,index=1,format=raw
> 
> ```
> 
> 
> 
> 控制台输出如下：
> 
> ```
> 
> (qemu:10668): Gtk-WARNING **: 16:01:57.231: Could not load a pixbuf from icon theme.
> 
> This may indicate that pixbuf loaders or the mime database could not be found.
> 
> ```
> 
> 
> 
> ![image](https://github.com/Goo-aw233/goo-aw233.github.io/assets/13451009/af4eee7b-9238-46d0-9914-2bd63438257c)
> 
> 
> 
> 

此外，如果添加了 -device virtio-gpu 这行参数，建议移除，因为 virtio-gpu 只在系统安装对应的驱动之后才会显示，且可能显示不正确，使用 ramfb 就够

文章中 -device virtio-gpu-pci ^ 这段应该被删除，但是我忘了（

**Comment by taozuhong** [comment]
> `-device virtio-gpu-pci`

删除这个参数后，执行命令后停留在 TianoCore 这一画面，不知道要等多久才能进入下一环节；

**Comment by taozuhong** [comment]
> > `-device virtio-gpu-pci`
> 
> 删除这个参数后，执行命令后停留在 TianoCore 这一画面，不知道要等多久才能进入下一环节；

貌似可以了，已经进入 Windows 安装环节了，不过速度太慢了，受不了
